resolver: lts-13.26

packages:
- .

extra-deps:
- purescript-0.13.8
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- hsc2hs-0.68.7

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
    quickcheck: false
